
INSERT INTO custom_options (categoria, label, preco)
SELECT v.categoria, v.label, v.preco::numeric
FROM (VALUES
  ('bordado_cano','Florência',25),('bordado_cano','Linhas',25),('bordado_cano','Peão Elite G',35),
  ('bordado_cano','Velho Barreiro',70),('bordado_cano','Rozeta',35),('bordado_cano','Nelore',25),
  ('bordado_cano','Cruz Bordada',25),('bordado_cano','Milionário',35),('bordado_cano','Monster',35),
  ('bordado_cano','Cruz Básica',25),('bordado_cano','Mulas',25),('bordado_cano','Ramos',25),
  ('bordado_cano','Peão Elite P',25),('bordado_cano','N. Senhora',25),('bordado_cano','Logo Marca',50),
  ('bordado_cano','N. Senhora P',10),('bordado_cano','Rozeta P',10),('bordado_cano','Cruz P',10),
  ('bordado_cano','Monster P',10),('bordado_cano','Bandeira P',15),
  ('bordado_cano','Bordado Variado R$5',5),('bordado_cano','Bordado Variado R$10',10),
  ('bordado_cano','Bordado Variado R$15',15),('bordado_cano','Bordado Variado R$20',20),
  ('bordado_cano','Bordado Variado R$25',25),('bordado_cano','Bordado Variado R$30',30),
  ('bordado_cano','Bordado Variado R$35',35),
  ('bordado_gaspea','Florência',15),('bordado_gaspea','Peão Elite G',20),('bordado_gaspea','Nelore',15),
  ('bordado_gaspea','Mulas',15),('bordado_gaspea','Cruz Bordada',15),('bordado_gaspea','Milionário',20),
  ('bordado_gaspea','Monster',20),('bordado_gaspea','Cruz Básica',15),('bordado_gaspea','Rozeta',20),
  ('bordado_gaspea','N. Senhora',20),('bordado_gaspea','Velho Barreiro',35),('bordado_gaspea','Peão Elite P',25),
  ('bordado_gaspea','Logo Marca',50),('bordado_gaspea','N. Senhora P',10),('bordado_gaspea','Rozeta P',10),
  ('bordado_gaspea','Cruz P',10),('bordado_gaspea','Monster P',10),('bordado_gaspea','Bandeira P',15),
  ('bordado_gaspea','Bordado Variado R$5',5),('bordado_gaspea','Bordado Variado R$10',10),
  ('bordado_gaspea','Bordado Variado R$15',15),('bordado_gaspea','Bordado Variado R$20',20),
  ('bordado_gaspea','Bordado Variado R$25',25),('bordado_gaspea','Bordado Variado R$30',30),
  ('bordado_gaspea','Bordado Variado R$35',35),
  ('bordado_taloneira','Florência',10),('bordado_taloneira','Nelore',10),('bordado_taloneira','Mulas',10),
  ('bordado_taloneira','Cruz Bordada',10),('bordado_taloneira','Peão Elite P',25),('bordado_taloneira','Logo Marca',50),
  ('bordado_taloneira','N. Senhora P',10),('bordado_taloneira','Rozeta P',10),('bordado_taloneira','Cruz P',10),
  ('bordado_taloneira','Monster P',10),('bordado_taloneira','Bandeira P',15),
  ('bordado_taloneira','Bordado Variado R$5',5),('bordado_taloneira','Bordado Variado R$10',10),
  ('bordado_taloneira','Bordado Variado R$15',15),('bordado_taloneira','Bordado Variado R$20',20),
  ('bordado_taloneira','Bordado Variado R$25',25),('bordado_taloneira','Bordado Variado R$30',30),
  ('bordado_taloneira','Bordado Variado R$35',35),
  ('laser_cano','Cruz',50),('laser_cano','Bridão',50),('laser_cano','Pipoco',50),('laser_cano','Ouro',50),
  ('laser_cano','Florência Brilhante',50),('laser_cano','Folhas',50),('laser_cano','Lara',50),
  ('laser_cano','Rodeio',50),('laser_cano','Iluminada',50),('laser_cano','Cruz Asas',50),
  ('laser_cano','Beca',50),('laser_cano','Coração',50),('laser_cano','Cruz Circular',50),
  ('laser_cano','Cruz Zero',50),('laser_cano','Borboleta',50),('laser_cano','Livia',50),
  ('laser_cano','Luiza',50),('laser_cano','Duquesa',50),('laser_cano','Julia',50),
  ('laser_cano','Anjo',50),('laser_cano','Pintura Cavalo',50),('laser_cano','Outro',50),
  ('laser_gaspea','Cruz',50),('laser_gaspea','Bridão',50),('laser_gaspea','Pipoco',50),('laser_gaspea','Ouro',50),
  ('laser_gaspea','Florência Brilhante',50),('laser_gaspea','Folhas',50),('laser_gaspea','Lara',50),
  ('laser_gaspea','Rodeio',50),('laser_gaspea','Iluminada',50),('laser_gaspea','Cruz Asas',50),
  ('laser_gaspea','Beca',50),('laser_gaspea','Coração',50),('laser_gaspea','Cruz Circular',50),
  ('laser_gaspea','Cruz Zero',50),('laser_gaspea','Borboleta',50),('laser_gaspea','Livia',50),
  ('laser_gaspea','Luiza',50),('laser_gaspea','Duquesa',50),('laser_gaspea','Julia',50),
  ('laser_gaspea','Anjo',50),('laser_gaspea','Pintura Cavalo',50),('laser_gaspea','Outro',50),
  ('laser_taloneira','Cruz',0),('laser_taloneira','Bridão',0),('laser_taloneira','Pipoco',0),('laser_taloneira','Ouro',0),
  ('laser_taloneira','Florência Brilhante',0),('laser_taloneira','Folhas',0),('laser_taloneira','Lara',0),
  ('laser_taloneira','Rodeio',0),('laser_taloneira','Iluminada',0),('laser_taloneira','Cruz Asas',0),
  ('laser_taloneira','Beca',0),('laser_taloneira','Coração',0),('laser_taloneira','Cruz Circular',0),
  ('laser_taloneira','Cruz Zero',0),('laser_taloneira','Borboleta',0),('laser_taloneira','Livia',0),
  ('laser_taloneira','Luiza',0),('laser_taloneira','Duquesa',0),('laser_taloneira','Julia',0),
  ('laser_taloneira','Anjo',0),('laser_taloneira','Pintura Cavalo',0),('laser_taloneira','Outro',0)
) AS v(categoria, label, preco)
WHERE NOT EXISTS (
  SELECT 1 FROM custom_options co WHERE co.categoria = v.categoria AND co.label = v.label
);
