// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://api.7estrivos.com.br";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV4cGNxcXhseXBzaGlja2FiZXlxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQxMjQxMDEsImV4cCI6MjA4OTcwMDEwMX0.jb-Ojq-PNzhW7wBotJQSOHClkflm7Cud5SL9tn3mkgk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});